import { type Product } from "../components/ProductCard";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod_1",
    title: "The Interstellar Explorer",
    price: 65.0,
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800",
    trailerVideo: "https://www.w3schools.com/html/mov_bbb.mp4",
    rating: 4.8,
    isBoxOfficeHit: true,
    genres: ["Sci-Fi", "Space"],
  },
  {
    id: "prod_2",
    title: "Neon Noir Runner",
    price: 75.0,
    image: "https://images.unsplash.com/photo-1578681994506-b8f463449011?auto=format&fit=crop&q=80&w=800",
    trailerVideo: "https://www.w3schools.com/html/mov_bbb.mp4",
    rating: 4.5,
    isBoxOfficeHit: false,
    genres: ["Cyberpunk", "Action"],
  },
  {
    id: "prod_3",
    title: "The Upside Down",
    price: 55.0,
    image: "https://images.unsplash.com/photo-1509927083803-4bd519298ac4?auto=format&fit=crop&q=80&w=800",
    trailerVideo: "https://www.w3schools.com/html/mov_bbb.mp4",
    rating: 4.9,
    isBoxOfficeHit: true,
    genres: ["Horror", "80s"],
  },
  {
    id: "prod_4",
    title: "Mafia Don Classic",
    price: 80.0,
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&q=80&w=800",
    trailerVideo: "https://www.w3schools.com/html/mov_bbb.mp4",
    rating: 4.2,
    isBoxOfficeHit: false,
    genres: ["Crime", "Drama"],
  },
  {
    id: "prod_5",
    title: "The Matrix Hacker",
    price: 70.0,
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&q=80&w=800",
    trailerVideo: "https://www.w3schools.com/html/mov_bbb.mp4",
    rating: 4.7,
    isBoxOfficeHit: true,
    genres: ["Sci-Fi", "Cyberpunk"],
  },
  {
    id: "prod_6",
    title: "Fantasy Ring Bearer",
    price: 85.0,
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800",
    trailerVideo: "https://www.w3schools.com/html/mov_bbb.mp4",
    rating: 4.9,
    isBoxOfficeHit: true,
    genres: ["Fantasy", "Adventure"],
  }
];
